services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile # This points to your Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@postgresDB:5432/UserDB?sslmode=disable
    depends_on:
      - postgresDB
    networks:
      - app_network
    
  postgresDB:
    image: postgres:16-alpine
    container_name: postgresDB
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: UserDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge